### ISSUE TITLE
关于切换bottomNavigationTabBar导致重绘的问题

### ISSUE THREAD

**Issue by changeyan** [iBotasky/Fybird#3]
您好,我看了你在flutter官方下的提问,并且在代码中加入了AutomaticKeepAliveClientMixin,且设置wantKeepAlive为true,在build return前写上了super.build(context),好像依然不起作用,所以我很好奇你是怎么解决的.

**Comment by changeyan** [comment]
我又看了一下你的代码,你是将tabbar放在了下面啊,难道改用tabbar就能解决问题?

**Comment by changeyan** [comment]
好吧,我又回来了,我看你发的问题里是使用的tabbar,但是我看你这个fybird里的底栏代码还是BottomNavigationTabbar,所以,还是想问你,解决了嘛

**Comment by iBotasky** [comment]
跟tabbar无关吧，这边只要实现了`AutomaticKeepAliveClientMixin`应该就没问题的。你可以贴一下你代码我帮你看一下

**Comment by changeyan** [comment]
家里太冷电脑在公司，去公司了我抽一下代码，贴出来，有QQ或者微信嘛，以后也可以一起交流一下😁，我QQ：476508065，wx：lenovoing

**Comment by iBotasky** [comment]
ok
